# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'az-connection'
              subscriptionId: 'b4f462dd-7c9b-4f7c-991b-ec079ba50b3d'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'Lab-RG'
              location: 'West US'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/ARMT/appgw.json'
              csmParametersFile: '$(Build.SourcesDirectory)/ARMT/db.json'
              overrideParameters: 'db'
              deploymentMode: 'Validation'
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'az-connection'
              subscriptionId: 'b4f462dd-7c9b-4f7c-991b-ec079ba50b3d'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'Lab-RG'
              location: 'West US'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/ARMT/webapp.json'
              csmParametersFile: '$(Build.SourcesDirectory)/ARMT/webapp.json'
              overrideParameters: 'webapp'
              deploymentMode: 'Validation'
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'az-connection'
              subscriptionId: 'b4f462dd-7c9b-4f7c-991b-ec079ba50b3d'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'Lab-RG'
              location: 'West US'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/ARMT/webapp.json'
              csmParametersFile: '$(Build.SourcesDirectory)/ARMT/appgw.json'
              overrideParameters: 'appgw'
              deploymentMode: 'Validation'